repos:
  - repo: local
    hooks:
      - id: black
        name: "black check"
        language: system
        entry: black . --check -q -tpy38
        verbose: true
        exclude: '(__init__.py$|^.ipython)'
        require_serial: true
        pass_filenames: false
        files: '\.py$'

      - id: isort
        name: "isort check"
        language: system
        entry: bash -c 'exec $USE_PYTHON -m isort . --check -q'
        args: [--check]
        verbose: true
        exclude: '__init__.py$'
        pass_filenames: false
        files: '\.py$'

      - id: flake8
        name: "Flake8 check"
        language: system
        entry: bash -c 'exec $USE_PYTHON -m flake8'
        verbose: true
        exclude: '__init__.py$'
        pass_filenames: false
        files: '\.py$'
