repos:
  - repo: local
    hooks:
      - id: black
        name: "black check"
        language: system
        entry:  bash -c 'exec $USE_PYTHON -m black . --check -q -tpy38'
        verbose: true
        exclude: ^(.ipython)
        require_serial: true
        pass_filenames: false
        files: \.py$

      - id: isort
        name: "isort check"
        language: system
        entry:  bash -c 'exec $USE_PYTHON -m isort . --check -q'
        args: [--check]
        verbose: true
        pass_filenames: false
        files: \.py$

      - id: flake8
        name: "Flake8 check"
        language: system
        entry:  bash -c 'exec $USE_PYTHON -m flake8'
        verbose: true
        pass_filenames: false
        files: \.py$
