url:
  imovirtual: "https://www.imovirtual.com/comprar/"

typology:
  imovirtual: [
    "apartamento", #3610
    "armazem",
    "escritorio",
    "garagem",
    "loja", #475
    "moradia", #2558
    "predio",
    "quintaeherdade", # 281
    "terreno", #2372
    "trespasse"
  ]

search:
  imovirtual: "/?search[order]=created_at_first%3Adesc&page="