name: Pull Request Linter

on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  lint-pr-title:
    runs-on: ubuntu-latest
    steps:
      - name: Lint PR Title
        uses: MorrisonCole/pr-lint-action@v1.7.0
        with:
          regex: '^(fix|feat|chore|docs|style|refactor|perf|test): .{1,50}$'
          token: ${{ secrets.GITHUB_TOKEN }}
